python run.py  --config-name=robocasa_config \
            --multirun agents=beso_agent \
            agent_name=beso_mamba \
            group=beso_decoder_only_benchmark \
            agents/model=beso/beso_dec_mamba \
            agents/obs_encoders=pretrained_resnet_film \
            agents.if_film_condition=True \
            mamba_n_layer_encoder=10 \
            seed=0,1,2