_target_: agents.ddim_agent.DDIM_Agent
_recursive_: false

defaults:
  - model: ddim/ddim_encdec_transformer_mamba.yaml
  - obs_encoders: resnet
  - language_encoders: clip

optimization:
  _target_: torch.optim.Adam
  lr: 1e-4
  weight_decay: 0

obs_seq_len: ${obs_seq_len}
act_seq_len: ${act_seq_len}

cam_names: ${camera_names}

if_robot_states: False
if_film_condition: False
device: ${device}
state_dim: ${obs_dim}
latent_dim: ${latent_dim}

# ---------------- DDIM 配置 ----------------
ddim_steps: 100         # 采样步数（可调）
eta: 0.0               # eta=0 → 确定性 DDIM；>0 → 随机性更强
