python run.py  --config-name=libero_config \
            --multirun agents=ddpm_agent \
            agent_name=ddpm_transformer \
            group=ddpm_decoder_only_benchmark \
            agents/model=ddpm/ddpm_dec_transformer \
            agents/obs_encoders=pretrained_resnet_film \
            agents.if_film_condition=True \
            task_suite=libero_10,libero_spatial \
            max_len_data=720 \
            traj_per_task=50 \
            seed=0,1,2
