_wandb:
    value:
        cli_version: 0.22.2
        e:
            rpg78pjxvior4r4b9nq1hq51vdc6foju:
                args:
                    - --config-name=robocasa_config
                    - sim_only=true
                    - agents=beso_agent
                    - seed=0
                    - hydra.job.chdir=false
                    - +checkpoint=/home/public/wyl/X_IL/ckpt_robocasa_seed0.pth
                codePath: run.py
                codePathLocal: run.py
                cpu_count: 28
                cpu_count_logical: 56
                cudaVersion: "11.8"
                disk:
                    /:
                        total: "172668043264"
                        used: "130782773248"
                email: 673269043@qq.com
                executable: /home/wyl/miniconda3/envs/xil/bin/python
                git:
                    commit: b2fef9e50aedbe1565b14474ab421680c316f04e
                    remote: https://github.com/ALRhub/X_IL.git
                gpu: NVIDIA GeForce GTX 1080 Ti
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 3584
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce GTX 1080 Ti
                      uuid: GPU-5971962f-7791-9a71-2be4-b68592020afb
                    - architecture: Pascal
                      cudaCores: 3584
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce GTX 1080 Ti
                      uuid: GPU-e8ed8a9d-822f-8a70-5f64-b006847ef53a
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-9b0226d9-2fff-0151-10a9-116b6886d6ca
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3080 Ti
                      uuid: GPU-d2e58c73-83cb-1753-612f-fdddd478406c
                host: admin123-SYS-4028GR-TR
                memory:
                    total: "202717921280"
                os: Linux-4.15.0-177-generic-x86_64-with-glibc2.27
                program: /home/public/wyl/X_IL/run.py
                python: CPython 3.10.18
                root: /home/public/wyl/X_IL
                startedAt: "2025-10-11T07:23:15.176582Z"
                writerId: rpg78pjxvior4r4b9nq1hq51vdc6foju
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 50
            "2":
                - 1
                - 41
                - 50
            "3":
                - 16
            "4": 3.10.18
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
Mamba_type:
    value: Mamba1
act_seq_len:
    value: 10
action_dim:
    value: 7
agent_name:
    value: beso
agents:
    value:
        _recursive_: false
        _target_: agents.beso_agent.BesoAgent
        act_seq_len: 10
        action_dim: 7
        cam_names:
            - robot0_agentview_left
            - robot0_agentview_right
            - robot0_eye_in_hand
        ckpt_path: null
        decay: 0.995
        device: cuda
        if_film_condition: false
        if_robot_states: false
        language_encoders:
            _recursive_: false
            _target_: agents.encoders.clip_lang_encoder.LangClip
            model_name: ViT-B/32
        latent_dim: 512
        lr_scheduler:
            lr_scheduler:
                final_lr_scale: 1e-06
                init_lr: 0.0001
                init_lr_scale: 0.1
                lr: 0.0001
                phase_ratio: (0.02, 0.08, 0.9)
                total_steps: 50000
        model:
            _recursive_: false
            _target_: agents.models.beso.models.edm_diffusion.score_wrappers.GCDenoiser
            inner_model:
                _recursive_: false
                _target_: agents.backbones.decoder_only.Noise_Dec_only
                action_dim: 7
                action_seq_len: 10
                device: cuda
                diffusion_type: beso
                embed_dim: 256
                embed_pdrob: 0
                encoder:
                    _target_: agents.backbones.xlstm.blocks.xLSTMBlockStack
                    adaLN_zero: false
                    chunkwise_kernel: parallel--native_autograd
                    embedding_dim: 256
                    in_context_cond: false
                    mode: train
                    num_blocks: 16
                    num_heads: 8
                    vocab_size: 0
                goal_conditioned: true
                goal_dim: 512
                goal_seq_len: 1
                linear_output: true
                obs_seq_len: 3
                state_dim: 512
                use_ada_conditioning: false
                use_pos_emb: true
            sigma_data: 0.5
        noise_scheduler: exponential
        num_sampling_steps: 4
        obs_encoders:
            _recursive_: false
            _target_: agents.encoders.multi_image_obs_encoder.MultiImageObsEncoder
            imagenet_norm: true
            random_crop: false
            resize_shape: null
            rgb_model:
                _target_: agents.encoders.resnets.BesoResNetEncoder
                latent_dim: 512
            shape_meta:
                obs:
                    robot0_agentview_left_image:
                        shape:
                            - 3
                            - 128
                            - 128
                        type: rgb
                    robot0_agentview_right_image:
                        shape:
                            - 3
                            - 128
                            - 128
                        type: rgb
                    robot0_eye_in_hand_image:
                        shape:
                            - 3
                            - 128
                            - 128
                        type: rgb
            share_rgb_model: false
            use_group_norm: true
        obs_seq_len: 1
        optimizer:
            _target_: torch.optim.AdamW
            betas:
                - 0.9
                - 0.9
            learning_rate: 0.0001
            obs_encoder_weight_decay: 0.05
            transformer_weight_decay: 0.05
        sampler_type: ddim
        sigma_data: 0.5
        sigma_max: 80
        sigma_min: 0.001
        sigma_sample_density_type: loglogistic
        use_lr_scheduler: false
        use_text_not_embedding: false
camera_names:
    value:
        - robot0_agentview_left
        - robot0_agentview_right
        - robot0_eye_in_hand
checkpoint:
    value: /home/public/wyl/X_IL/ckpt_robocasa_seed0.pth
dataset_path:
    value: /home/public/wyl/X_IL/robocasa/datasets/v0.1/single_stage/
decoder_n_layer:
    value: 6
device:
    value: cuda
encoder_n_layer:
    value: 4
env_name:
    value:
        - PnPCabToCounter
        - PnPStoveToCounter
epoch:
    value: 100
eval_every_n_epochs:
    value: 1
global_action:
    value: false
goal_conditioned:
    value: true
goal_dim:
    value: 512
goal_window_size:
    value: 1
group:
    value: bc_robocasa
if_robot_states:
    value: false
if_use_ema:
    value: true
img_height:
    value: 128
img_width:
    value: 128
latent_dim:
    value: 512
log_dir:
    value: logs/robocasa/
mamba_decoder_cfg:
    value:
        d_conv: 4
        d_state: 64
        expand: 2
        layer: Mamba1
mamba_encoder_cfg:
    value:
        d_conv: 4
        d_state: 64
        expand: 2
        layer: Mamba1
mamba_n_layer_decoder:
    value: 8
mamba_n_layer_encoder:
    value: 4
max_len_data:
    value: 260
multistep:
    value: 10
n_embd:
    value: 256
n_heads:
    value: 4
num_sampling_steps:
    value: 4
num_workers:
    value: 24
obs_dim:
    value: 13
obs_seq_len:
    value: 1
obs_tokens:
    value: 3
pred_seq_len:
    value: 10
scale_data:
    value: true
scaler_type:
    value: standard
seed:
    value: 0
shape_meta:
    value:
        obs:
            robot0_agentview_left_image:
                shape:
                    - 3
                    - 128
                    - 128
                type: rgb
            robot0_agentview_right_image:
                shape:
                    - 3
                    - 128
                    - 128
                type: rgb
            robot0_eye_in_hand_image:
                shape:
                    - 3
                    - 128
                    - 128
                type: rgb
sim_only:
    value: true
simulation:
    value:
        _target_: simulation.robocasa_sim.RoboCasaSim
        camera_names:
            - robot0_agentview_left
            - robot0_agentview_right
            - robot0_eye_in_hand
        device: cuda
        env_name:
            - PnPCabToCounter
            - PnPStoveToCounter
        global_action: false
        if_vision: true
        img_height: 128
        img_width: 128
        max_step_per_episode: 400
        n_cores: 1
        num_episode: 1
        render: true
        seed: 0
state_dim:
    value: 0
train_batch_size:
    value: 256
trainers:
    value:
        _recursive_: false
        _target_: trainers.base_trainer.BaseTrainer
        decay_ema: 0.995
        device: cuda
        epoch: 100
        eval_every_n_epochs: 1
        if_use_ema: true
        num_workers: 24
        obs_seq_len: 1
        scale_data: true
        scaler_type: standard
        train_batch_size: 256
        trainset:
            _target_: environments.dataset.robocasa_dataset_memory.RobocasaDataset
            action_dim: 7
            cam_names:
                - robot0_agentview_left
                - robot0_agentview_right
                - robot0_eye_in_hand
            data_directory: /home/public/wyl/X_IL/robocasa/datasets/v0.1/single_stage/
            device: cuda
            env_name:
                - PnPCabToCounter
                - PnPStoveToCounter
            global_action: false
            max_len_data: 260
            obs_dim: 13
            window_size: 10
        val_batch_size: 64
        valset:
            _target_: environments.dataset.robocasa_dataset_memory.RobocasaDataset
            action_dim: 7
            cam_names:
                - robot0_agentview_left
                - robot0_agentview_right
                - robot0_eye_in_hand
            data_directory: /home/public/wyl/X_IL/robocasa/datasets/v0.1/single_stage/
            device: cuda
            env_name:
                - PnPCabToCounter
                - PnPStoveToCounter
            global_action: false
            max_len_data: 260
            obs_dim: 13
            window_size: 10
trainset:
    value:
        _target_: environments.dataset.robocasa_dataset_memory.RobocasaDataset
        action_dim: 7
        cam_names:
            - robot0_agentview_left
            - robot0_agentview_right
            - robot0_eye_in_hand
        data_directory: /home/public/wyl/X_IL/robocasa/datasets/v0.1/single_stage/
        device: cuda
        env_name:
            - PnPCabToCounter
            - PnPStoveToCounter
        global_action: false
        max_len_data: 260
        obs_dim: 13
        window_size: 10
traj_per_task:
    value: 0
use_pos_emb:
    value: true
val_batch_size:
    value: 64
val_start_idx:
    value: 0
valset:
    value:
        _target_: environments.dataset.robocasa_dataset_memory.RobocasaDataset
        action_dim: 7
        cam_names:
            - robot0_agentview_left
            - robot0_agentview_right
            - robot0_eye_in_hand
        data_directory: /home/public/wyl/X_IL/robocasa/datasets/v0.1/single_stage/
        device: cuda
        env_name:
            - PnPCabToCounter
            - PnPStoveToCounter
        global_action: false
        max_len_data: 260
        obs_dim: 13
        window_size: 10
wandb:
    value:
        entity: 673269043-wuhan-university-of-science-and-technology
        project: fast_mail_robocasa
window_size:
    value: 10
xlstm_decoder_adaLN_zero:
    value: false
xlstm_decoder_blocks:
    value: 16
xlstm_decoder_chunkwise_kernel:
    value: parallel--native_autograd
xlstm_decoder_in_context_cond:
    value: false
xlstm_decoder_mode:
    value: train
xlstm_decoder_vocab_size:
    value: 0
xlstm_encoder_adaLN_zero:
    value: false
xlstm_encoder_blocks:
    value: 16
xlstm_encoder_chunkwise_kernel:
    value: parallel--native_autograd
xlstm_encoder_in_context_cond:
    value: false
xlstm_encoder_mode:
    value: train
xlstm_encoder_vocab_size:
    value: 0
