python run.py  --config-name=libero_horeka_config \
            --multirun agents=beso_agent \
            agent_name=beso_transformer \
            group=beso_encoder_decoder \
            agents/model=beso/beso_encdec_transformer \
            task_suite=libero_object,libero_goal,libero_10,libero_spatial \
            traj_per_task=10,50 \
            encoder_n_layer=4 \
            decoder_n_layer=6 \
            seed=0,1,2