python run.py  --config-name=libero_horeka_config \
            --multirun agents=beso_agent \
            agent_name=beso_xlstm \
            group=beso_encoder_decoder \
            agents/model=beso/beso_encdec_xlstm \
            task_suite=libero_10,libero_spatial \
            traj_per_task=10,50 \
            xlstm_encoder_blocks=6,8 \
            xlstm_decoder_blocks=6,8 \
            seed=0,1,2